name: 🏭 Cut Mod Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Semver Bump Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  cut_release:
    name: "Cut Release"
    uses: open-goal/mod-bundling-tools/.github/workflows/mod-bundler.yml@v1
    with:
      semverBump: ${{ inputs.bump }}
      metadataName: "Skull gems autocollector"
      metadataDescription: "Autocollects skull gems whenever a metalhead is killed"
      metadataSupportedGames: "jak2"
      metadataAuthors: "comba92"
      metadataTags: "quality-of-life"
      metadataWebsiteUrl: "https://www.example.com/please/change/me"
      toolingRepo: "OpenGOAL-Mods/OG-Mod-Base"
      gameAssetsDir: "game/assets"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
